### ISSUE TITLE
Error authClient config

### ISSUE THREAD

**Issue by tecnoterabyte** [yiisoft/yii-auth-client#11]
### What steps will reproduce the problem?
```
return [
	'authClientCollection' => [
		'__class' => yii\authclient\Collection::class,
		'clients' => [
			'facebook' => [
				'__class'      => yii\authclient\clients\Facebook::class,
				'clientId'     => 'CLIENT_ID',
				'clientSecret' => 'CLIENT_SECRET',
			],
		],
	],
];
```

### What's expected?
Client Facebook

### What do you get instead?
```
Exception 'Error' with message 'Cannot access private property yii\authclient\Collection::$clients' 

in D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\di\src\AbstractContainer.php:396

Stack trace:
#0 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\di\src\AbstractContainer.php(362): yii\di\AbstractContainer::configure(Object(yii\authclient\Collection), Array)
#1 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\di\src\AbstractContainer.php(189): yii\di\AbstractContainer->buildFromConfig('authClientColle...', Array)
#2 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\di\src\AbstractContainer.php(131): yii\di\AbstractContainer->buildWithDefinition('authClientColle...', Array, Array)
#3 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\di\src\Container.php(55): yii\di\AbstractContainer->build('authClientColle...')
#4 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\yii-core\src\base\Module.php(805): yii\di\Container->get('authClientColle...')
#5 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\yii-auth-client\src\widgets\AuthChoice.php(154): yii\base\Module->get('authClientColle...')
#6 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\yii-auth-client\src\widgets\AuthChoice.php(121): yii\authclient\widgets\AuthChoice->defaultClients()
#7 D:\Program Files\webs\terabytesoft\app-user\src\views\security\login.php(176): yii\authclient\widgets\AuthChoice->getClients()
#8 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\view\src\view\View.php(363): require('D:\\Program File...')
#9 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\view\src\view\View.php(239): yii\view\View->renderPhpFile('D:\\Program File...', Array)
#10 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\view\src\view\View.php(138): yii\view\View->renderFile('D:\\Program File...', Array, Object(app\user\controllers\SecurityController))
#11 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\yii-web\src\Controller.php(97): yii\view\View->render('login', Array, Object(app\user\controllers\SecurityController))
#12 D:\Program Files\webs\terabytesoft\app-user\src\controllers\SecurityController.php(98): yii\web\Controller->render('login', Array)
#13 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\yii-core\src\base\InlineAction.php(56): app\user\controllers\SecurityController->actionLogin()
#14 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\yii-core\src\base\Controller.php(160): yii\base\InlineAction->runWithParams(Array)
#15 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\yii-core\src\base\Module.php(542): yii\base\Controller->runAction('login', Array)
#16 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\yii-web\src\Application.php(94): yii\base\Module->runAction('user/security/l...', Array)
#17 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\yii-core\src\base\Application.php(544): yii\web\Application->handleRequest(Object(yii\web\Request))
#18 D:\Program Files\webs\terabytesoft\app-user\tests\public\index.php(21): yii\base\Application->run()
#19 D:\Program Files\webs\terabytesoft\app-user\tests\public\index.php(22): {closure}()
#20 {main}
```

Change Colletion.php:

```
private $clients = []; --> public $clients = [];

Exception 'TypeError' with message 'Return value of yii\authclient\Collection::getClient() must be an instance of yii\authclient\ClientInterface, array returned' 

in D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\yii-auth-client\src\Collection.php:84

Stack trace:
#0 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\yii-auth-client\src\Collection.php(65): yii\authclient\Collection->getClient('facebook')
#1 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\yii-auth-client\src\widgets\AuthChoice.php(156): yii\authclient\Collection->getClients()
#2 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\yii-auth-client\src\widgets\AuthChoice.php(121): yii\authclient\widgets\AuthChoice->defaultClients()
#3 D:\Program Files\webs\terabytesoft\app-user\src\views\security\login.php(176): yii\authclient\widgets\AuthChoice->getClients()
#4 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\view\src\view\View.php(363): require('D:\\Program File...')
#5 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\view\src\view\View.php(239): yii\view\View->renderPhpFile('D:\\Program File...', Array)
#6 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\view\src\view\View.php(138): yii\view\View->renderFile('D:\\Program File...', Array, Object(app\user\controllers\SecurityController))
#7 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\yii-web\src\Controller.php(97): yii\view\View->render('login', Array, Object(app\user\controllers\SecurityController))
#8 D:\Program Files\webs\terabytesoft\app-user\src\controllers\SecurityController.php(98): yii\web\Controller->render('login', Array)
#9 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\yii-core\src\base\InlineAction.php(56): app\user\controllers\SecurityController->actionLogin()
#10 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\yii-core\src\base\Controller.php(160): yii\base\InlineAction->runWithParams(Array)
#11 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\yii-core\src\base\Module.php(542): yii\base\Controller->runAction('login', Array)
#12 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\yii-web\src\Application.php(94): yii\base\Module->runAction('user/security/l...', Array)
#13 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\yii-core\src\base\Application.php(544): yii\web\Application->handleRequest(Object(yii\web\Request))
#14 D:\Program Files\webs\terabytesoft\app-user\tests\public\index.php(21): yii\base\Application->run()
#15 D:\Program Files\webs\terabytesoft\app-user\tests\public\index.php(22): {closure}()
#16 {main}
```

### Additional info

| Q                       | A
| ----------------------- | ---
| Yii version             | 3.0
| Yii Auth Client version | 3.0 
| Yii HTTP Client version | 3.0
| PHP version             | 7.1.23
| Operating system        | Centos 7.0

**Comment by samdark** [comment]
https://github.com/yiisoft/yii-auth-client/blob/master/src/Collection.php#L21

**Comment by tecnoterabyte** [comment]
> https://github.com/yiisoft/yii-auth-client/blob/master/src/Collection.php#L21

setClients no works also probe it. returns a blank empty.

**Comment by samdark** [comment]
Right. Should add `()` as `setClients()`.

**Comment by tecnoterabyte** [comment]
> Right. Should add `()` as `setClients()`.

```
Exception 'TypeError' with message 'Return value of yii\authclient\Collection::getClient() must be an instance of yii\authclient\ClientInterface, string returned' 

in D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\yii-auth-client\src\Collection.php:84

Stack trace:
#0 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\yii-auth-client\src\Collection.php(65): yii\authclient\Collection->getClient('__class')
#1 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\yii-auth-client\src\widgets\AuthChoice.php(156): yii\authclient\Collection->getClients()
#2 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\yii-auth-client\src\widgets\AuthChoice.php(121): yii\authclient\widgets\AuthChoice->defaultClients()
#3 D:\Program Files\webs\terabytesoft\app-user\src\views\security\login.php(176): yii\authclient\widgets\AuthChoice->getClients()
#4 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\view\src\view\View.php(363): require('D:\\Program File...')
#5 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\view\src\view\View.php(239): yii\view\View->renderPhpFile('D:\\Program File...', Array)
#6 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\view\src\view\View.php(138): yii\view\View->renderFile('D:\\Program File...', Array, Object(app\user\controllers\SecurityController))
#7 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\yii-web\src\Controller.php(97): yii\view\View->render('login', Array, Object(app\user\controllers\SecurityController))
#8 D:\Program Files\webs\terabytesoft\app-user\src\controllers\SecurityController.php(98): yii\web\Controller->render('login', Array)
#9 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\yii-core\src\base\InlineAction.php(56): app\user\controllers\SecurityController->actionLogin()
#10 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\yii-core\src\base\Controller.php(160): yii\base\InlineAction->runWithParams(Array)
#11 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\yii-core\src\base\Module.php(542): yii\base\Controller->runAction('login', Array)
#12 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\yii-web\src\Application.php(94): yii\base\Module->runAction('user/security/l...', Array)
#13 D:\Program Files\webs\terabytesoft\app-user\vendor\yiisoft\yii-core\src\base\Application.php(544): yii\web\Application->handleRequest(Object(yii\web\Request))
#14 D:\Program Files\webs\terabytesoft\app-user\tests\public\index.php(21): yii\base\Application->run()
#15 D:\Program Files\webs\terabytesoft\app-user\tests\public\index.php(22): {closure}()
#16 {main}
```

**Comment by tecnoterabyte** [comment]
When the extension was updated, AuthChoice.php was not updated, referencing $client->getId() when it was removed in Collection.php https://github.com/yiisoft/yii-auth-client/blob/976e0f55232450226c3daf29c87ea32a6384fe50/src/widgets/AuthChoice.php#L234

**Comment by rustamwin** [comment]
This issue is out of date.
